name: Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: godebos/debos:main
    steps:
      - uses: actions/checkout@v3
      - name: Start Build
        run: |
          debos debian-ostree.yaml