name: Build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: godebos/debos:main
    steps:
      - name: Start Build
        runs: |
          ls
          debos debian-ostree.yaml